# Use '' to indicate the filed is empty
input_dir: ./data_ST/day1
output_dir: ./analysis_result/
test_run: false


experiment:
    # when you're confused about glob pattern, see also
    # https://note.nkmk.me/python-glob-usage/
    file_pattern: day[1-5]_t[1-6].pkl
    param_pattern: day[1-5]_t[1-6]_param.pkl
    eye_pattern: eyeclosed.txt

    ignore_pattern: 'day5_t[1-2].pkl'
    ignore_files:
        - 'day4_t3.pkl'

    n_Ch: 129
    n_Trial: 25
    n_Session: 6
    Ref_ch: 
        - 57
        - 100
    COI:
        - 7
        - 31
        - 36
        - 55
        - 80
        - 104
        - 105
        - 106
        - 112
        - 129
#   [6 13 112 7 106 30 105 31 80 37 87 55 54 79 129]

filter:
    Fs: 1000
    Bandpass:
        - 0.01
        - 20
    Notch: 
        - 49
        - 51
    butter_N: 3
